version: '3'

tasks:
  test:
    - cls
    - pytest -v __tests 
  lint:
   - ruff check .

  test-cov:
    - coverage run  -m pytest __tests/
    - coverage combine
    - coverage report -m

  dist: 
    - poetry build

  rel: 
    - task: dist
    - poetry publish

  dev-ins: poetry install
